### ISSUE TITLE
Merge with PopcornTime/Android?

### ISSUE THREAD

**Issue by zenware** [se-bastiaan/PopcornTimeRemote-Android#95]
I think it would be awesome if this control functionality was in the full popcorn time app on Android. Being one app is the biggest benefit for me, but with the display built into the current app I envision being able to pick some content and choosing whether to stream it to a chrome cast from your phone  or computer rather than currently just operating a computer that is in line of sight, which is almost never what I use your remote for and it's rather painful to operate that way as is.

**Comment by aleksandar-todorovic** [comment]
I have to strongly disagree because it would actually be the worst case scenario for the users with low end Android devices like me.

First of all, this app is small in size and it takes like no RAM. It does one thing, but it does it great.

If it gets merged, I'll have to download the original Popcorn Time app which is resource hungry, takes a considerable size on low end devices (and those who are running 4.1 versions of Android couldn't transfer it to an external memory card) and is practically unusable on slower devices.

This way, I could have the best of both worlds. If it gets merged, I'll get nothing.
